// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BookingConfirmer is an autogenerated mock type for the BookingConfirmer type
type BookingConfirmer struct {
	mock.Mock
}

// ConfirmBooking provides a mock function with given fields: eventID, userID
func (_m *BookingConfirmer) ConfirmBooking(eventID int, userID string) error {
	ret := _m.Called(eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(eventID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookingConfirmer creates a new instance of BookingConfirmer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingConfirmer(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingConfirmer {
	mock := &BookingConfirmer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
