// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BookingCreator is an autogenerated mock type for the BookingCreator type
type BookingCreator struct {
	mock.Mock
}

// BookEvent provides a mock function with given fields: eventID, userID
func (_m *BookingCreator) BookEvent(eventID int, userID string) error {
	ret := _m.Called(eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for BookEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(eventID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookingCreator creates a new instance of BookingCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingCreator {
	mock := &BookingCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
