// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	models "eventBooker/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// EventsGetter is an autogenerated mock type for the EventsGetter type
type EventsGetter struct {
	mock.Mock
}

// GetAllEvents provides a mock function with no fields
func (_m *EventsGetter) GetAllEvents() ([]models.Event, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllEvents")
	}

	var r0 []models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Event, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventsGetter creates a new instance of EventsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventsGetter {
	mock := &EventsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
